### ISSUE TITLE
réalisation de la carte

### ISSUE THREAD

**Issue by GuyliannEngels** [JulieCantineau/covid-19#1]
Salut à tous,

voila un auto sympa sur la réalisation de carte dans R 

<https://tvroylandt.github.io/r-cartostat/index.html>

Pour trouver le fond de carte @damien-dumont  a une astuce

**Comment by damien-dumont** [comment]
Bonjour,

Pour la réalisation d'une carte, j'ai pu me servir de [ce site](https://www.woutervandooren.eu/post/20190222_map_rstat/), qui a été fait par un Belge néérlandophone (mais le site est en anglais). L'avantage est qu'il applique ses méthodes au cas précis de la Belgique, ce qui nous intéresse.

Dans l'article, il indique comment faire pour obtenir les données sur les cartes, mais seulement de façon très vague. Après d'âpres recherchers, j'ai cependant [trouvé les données que nous cherchons](https://finances.belgium.be/fr/particuliers/habitation/cadastre/plan-cadastral/lambert-2008/2019) sur le site du SPF finances. Les cartes sont à jour de juin 2019. Pour télécharger le pack, il suffit de cliquer sur "Limites administratives". Je m'attèle à lire les informations contenue dans le fichier dès que possible.

**Comment by damien-dumont** [comment]
Alors, autant pour moi, mais je pense qu'il ne faut pas cliquer sur "Limites administratives" mais bien "Toute la belgique". Sinon, on obtient juste les frontières. C'est bien marrant, mais sans données (par exemple, code postal de la commune), impossible d'y appliquer des données. C'est donc bien sur "Toute la belgique" qu'il faut cliquer, mais celà donne un fichier de + de 2 giga. C'est très lourd pour un PC, donc je le téléchargerai sur mon pc fixe personnel. J'espère juste que les fichiers de cartes resteront assez petits pour github. 

TLDR: téléchargez rien, je met les cartes moi même, on jouera avec après.

**Comment by GuyliannEngels** [comment]
Pour télecharger les carte, j'ai trouvé pour ma part [AdminVector](https://www.geo.be/#!/catalog/details/fb1e2993-2020-428c-9188-eb5f75e284b9?l=fr). Il s'agit des cartes au format vectorielle proposé par l'IGN (donc on est sur que c'est précis, mais peut être un peu trop :p)

J'ai regardé à la license et dans le cadre public sans commercialisation du produit. Il suffit de respecter la bonne manière de citer ce produit. 

@damien-dumont , tu as regardé à la license de tes fonds de carte ?

**Comment by damien-dumont** [comment]
@GuyliannEngels les conditions d'utilisations sont sous format PDF dans le dossier rar que j'utilise, je cite 

> 1. Sous réserve du respect des termes et conditions d'utilisation de la présente
Licence, le SPF Finances vous autorise à exercer pour le monde entier, à titre
gratuit, non sous-licenciable, non exclusif, les droits accordés par la présente
licence afin de :
A. reproduire et partager le plan cadastral, en tout ou partie ; et
B. produire, reproduire et partager l’Oeuvre dérivée.

de la même manière en citant correctement, mais tout est expliqué dans le PDF.

Mais je vais quand même utiliser AdminVector car celui que j'ai trouvé m'a l'air inadapté à R.

**Comment by GuyliannEngels** [comment]
J'ai trouvé un truc de bien sympa pour travailler avec les carte de AdminVector :)

Si vous avez testé de réalise une carte avec une instruction de ce type 

```
map <- sf::st_read("data/raw/adminvectorwgs/AD_2_Municipality.shp")

ggplot(map) +
    geom_sf()
```

Vous allez vous rendre compte que cela prend du temps, beaucoup trop de temps à mon gout pour pouvoir l'utiliser de manière pratique dans la réalisation d'une app shiny. avec l'instruction pryr::object_size(), vous allez pouvoir prendre connaissance de la taille de l'objet.

```
pryr::object_size(map)
# > pryr::object_size(map)
# 17.4 MB
```

Tout s'explique, le graphique utilise un fichier source de 17.4 MB. J'ai un peu cherché et il existe une fonction pour simplifier un objet sf. 

```
map_red <- sf::st_simplify(map, dTolerance = 0.001)
pryr::object_size(map_red)
# > pryr::object_size(map_red)
# 1.29MB 
```

1.29 c'est toujours beaucoup mais il s'agit d'une carte des communes de belgique soit plus de 580 zones à représenter.
